stages:
  - test
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TWINE_USERNAME: "gitlab-ci-token"
  TWINE_PASSWORD: "$CI_JOB_TOKEN"

cache:
  paths:
    - .cache/pip
    - .venv/

default:
  image: almalinux:10-kitten

test:
  stage: test
  script:
    - dnf install -y 'dnf-command(config-manager)' && dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm && dnf -y config-manager  --set-enabled pgdg-rhel10-extras && dnf -y update && dnf -y install etcd make python
    - etcd &
    - pip install uv
    - uv sync
    - make test

build:
  stage: build
  script:
    - uv build
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week

publish:
  stage: publish
  script:
    - pip install twine
    - twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG

